steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '--build-arg', 'NEXT_PUBLIC_API_BASE_URL=$_NEXT_PUBLIC_API_BASE_URL',
    '-t', 'gcr.io/$PROJECT_ID/singlelineiq-frontend',
    '.'
  ]
images:
- 'gcr.io/$PROJECT_ID/singlelineiq-frontend'
